# Use These Various From ProgramMain.py
USE_OPENCV_VERSION = "3.2.0"
OBJECT_DETECT_TESTCASE_PATH = "Tests/testcase5/"
FIND_CORNER_TESTCASE_PATH = "Tests/testcase7/"

# Use These Various From ObjectDetect.py
MORPHOLOGY_MASK_SIZE = 5
BLUR_MASK_SIZE = 3
EACH_IMAGE_DIFFERENCE_THRESHOLD = 30
SET_IMAGE_WHITE_COLOR = 255
SET_IMAGE_BLACK_COLOR = 0
NEIGHBORHOOD_MASK_SIZE = 7
CANNY_MINIMUM_THRESHOLD = 100
CANNY_MAXIMUM_THRESHOLD = 150
GET_MAXIMUM_AREA_SIZE = 5
SQUARE_CORNER_NUM = 4
IMAGE_WIDTH = 294.0

# Use These Various From LogManager.py
LOG_LEVEL_DEBUG = 0
LOG_LEVEL_INFO = 1
LOG_LEVEL_WARN = 2
LOG_LEVEL_ERROR = 3